wsgi_apps/datacatalog/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
#from django.contrib import admin
#admin.autodiscover()

urlpatterns = patterns('',
    #url(r'^getempty/','datacatalog.editCat.views.empty_Load', name='empty_Load'),
    # Example:
    # (r'^example/', include('example.foo.urls')),
#    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'editCat/login.html'}),
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    #url(r'', 'datacatalog.editCat.views.main_commons', name='commons'),
    url(r'^$', 'datacatalog.editCat.views.main_commons', name='commons'),
    url(r'^catalog/','datacatalog.editCat.views.catalog', name='catalog'),
    url(r'^commons/','datacatalog.editCat.views.main_catalog', name='commons'),
    url(r'^common/','datacatalog.editCat.views.load_common', name='commons'),
    url(r'^event/','datacatalog.editCat.views.load_event', name='events'),
# Ajax Calls
    url(r'^getcommon/','datacatalog.editCat.views.ajax_com', name='ajax_com'),
    url(r'^delcommon/','datacatalog.editCat.views.ajax_com_del', name='ajax_com_del'),
    url(r'^getcatalog/','datacatalog.editCat.views.ajax_cat', name='ajax_cat'),
    url(r'^delcatalog/','datacatalog.editCat.views.ajax_cat_del', name='ajax_cat_del'),
    url(r'^getevent/','datacatalog.editCat.views.ajax_event', name='ajax_event'),
    url(r'^delevent/','datacatalog.editCat.views.ajax_event_del', name='ajax_event_del'),
    url(r'^getresult/','datacatalog.editCat.views.ajax_result', name='ajax_result'),
    url(r'^delresult/','datacatalog.editCat.views.ajax_result_del', name='ajax_result_del'),
    url(r'^getlocation/','datacatalog.editCat.views.ajax_loc', name='ajax_loc'),
    url(r'^getmethod/','datacatalog.editCat.views.ajax_meth', name='ajax_meth'),
    url(r'^getmethPar/','datacatalog.editCat.views.ajax_methPar', name='ajax_methPar'),
    url(r'^gettype/','datacatalog.editCat.views.ajax_type', name='ajax_type'),
    url(r'^getvar/','datacatalog.editCat.views.ajax_var', name='ajax_var'),
    url(r'^getws_view/','datacatalog.editCat.views.webservice_view', name='ajax_ws_view'),
    url(r'^getempty/','datacatalog.editCat.views.empty_Load', name='empty_Load'),
#webservice_view
# login
    #url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'registration/login.html'}),
    #url(r'^accounts/logout/accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'registration/login.html'}),
    #url(r'^accounts/logout/$','datacatalog.editCat.views.logout_view', name='logout'),
    #url(r'^accounts/login/createnewuser/$', 'datacatalog.editCat.views.new_user',name='new_user'),
# Uncomment the next line to enable the admin:
    # (r'^admin/(.*)', admin.site.root),
    #('^$', 'rpc4django.views.serve_rpc_request'),
    ('^RPC/$', 'rpc4django.views.serve_rpc_request'),
    # Uncomment the admin/doc line below to enable admin documentation:
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    #url(r'^admin/', include(admin.site.urls)),
)

wsgi_apps/datacatalog/editCat/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#     * Rearrange models' order
#     * Make sure each model has one field with primary_key=True
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin.py sqlcustom [appname]'
# into your database.

from django.db import models
from django.forms import ModelForm
from django import forms
import datetime

class RtState(models.Model):
    state_code = models.CharField(max_length=10, primary_key=True)
    state_name = models.CharField(max_length=255)
    status_flag = models.CharField(max_length=1)
    remark = models.CharField(max_length=2000)
    class Meta:
        db_table = u'rt_state'

class RtResultType(models.Model):
    result_type_code = models.CharField(max_length=20, primary_key=True)
    result_type_desc = models.CharField(max_length=255)
    status_flag = models.CharField(max_length=1)
    remark = models.CharField(max_length=2000)
    class Meta:
        db_table = u'rt_result_type'

class RtOrganizationType(models.Model):
    org_type = models.CharField(max_length=20, primary_key=True)
    org_type_desc = models.CharField(max_length=255)
    status_flag = models.CharField(max_length=1)
    remark = models.CharField(max_length=2000)
    class Meta:
        db_table = u'rt_organization_type'

class DtDataCommons(models.Model):
    Status_Data_Choices = (('A','Active'),('I','Inactive'),)
    commons_id = models.AutoField(primary_key=True)
    commons_code = models.CharField(max_length=20)
    commons_type = models.CharField(max_length=20, null=True, blank=True)
    data_provider = models.CharField(max_length=20,null=True,blank=True)
    program_code = models.CharField(max_length=20, null=True, blank=True)
    commons_name = models.CharField(max_length=60, blank=True)
    commons_desc = models.CharField(max_length=2000, blank=True)
    start_date = models.DateTimeField(null=True, blank=True)
    status_flag = models.CharField(max_length=1, blank=True, null=True, choices=Status_Data_Choices, default='A')
    def save(self):
        if self.commons_type=='': self.commons_type=None
        if self.data_provider=='': self.data_provider=None
        if self.program_code=='': self.program_code=None
        if self.commons_desc=='': self.commons_desc=None
        if self.status_flag=='': self.status_flag=None
        
        super(DtDataCommons,self).save()

    def __unicode__(self):
        return u'%s %s' % (self.commons_id, self.commons_name)
    class Meta:
        db_table = u'dt_data_commons'

class RtVariables(models.Model):
    var_id = models.CharField(max_length=30, primary_key=True)
    variable_name = models.CharField(max_length=255)
    sort_order = models.IntegerField(null=True,blank=True)
    variable_type = models.CharField(max_length=30,null=True,blank=True)
    status_flag = models.CharField(max_length=1)
    var_short_name = models.CharField(max_length=30,null=True,blank=True)
    remark = models.CharField(max_length=2000,null=True,blank=True)
    userid = models.CharField(max_length=20)
    def __unicode__(self):
        return u'(%s) -  %s' % (self.var_id, self.variable_name)
    class Meta:
        db_table = u'rt_variables'

class DtType(models.Model):
    type_id = models.CharField(max_length=40, primary_key=True)
    type_name = models.CharField(max_length=255)
    product = models.CharField(max_length=255,blank=True, null=True)
    description = models.CharField(max_length=255,blank=True, null=True)
    resolution = models.CharField(max_length=255,blank=True, null=True)
    res_unit = models.CharField(max_length=50,blank=True, null=True)
    object_type = models.CharField(max_length=100,blank=True, null=True)
    object_data_type1 = models.CharField(max_length=255,blank=True, null=True)
    object_data_opt1_unit = models.CharField(max_length=100,blank=True, null=True)
    userid = models.CharField(max_length=20)
    def save(self):
        if self.product=='': self.product=None
        if self.description=='': self.description=None
        if self.resolution=='': self.resolution=None
        if self.res_unit=='': self.res_unit=None
        if self.object_type=='': self.object_type=None
        if self.object_data_type1=='': self.object_data_type1=None
        if self.object_data_opt1_unit=='': self.object_data_opt1_unit=None
        super(DtType,self).save()
    def __unicode__(self):
        return u'%s %s' % (self.type_id, self.type_name)
    class Meta:
        db_table = u'dt_type'

class SchemaVersion(models.Model):
    key = models.CharField(max_length=255, primary_key=True)
    timestamp = models.DateTimeField()
    extra = models.CharField(max_length=255)
    sfile = models.CharField(max_length=255)
    class Meta:
        db_table = u'schema_version'

class RtOrganization(models.Model):
    org_code = models.CharField(max_length=20, primary_key=True)
    org_name = models.CharField(max_length=255)
    org_type = models.ForeignKey(RtOrganizationType, db_column='org_type')
    status_flag = models.CharField(max_length=1)
    remark = models.CharField(max_length=2000)
    class Meta:
        db_table = u'rt_organization'

class DtPeople(models.Model):
    people_id = models.IntegerField(primary_key=True)
    person_name = models.CharField(max_length=255)
    title = models.CharField(max_length=100)
    address1 = models.CharField(max_length=80)
    address2 = models.CharField(max_length=80)
    city = models.CharField(max_length=40)
    state = models.ForeignKey(RtState, db_column='state')
    postal_code = models.CharField(max_length=15)
    country = models.CharField(max_length=80)
    phone_number = models.CharField(max_length=20)
    email = models.CharField(max_length=100)
    org_code = models.ForeignKey(RtOrganization, db_column='org_code')
    class Meta:
        db_table = u'dt_people'

class RtLocationType(models.Model):
    location_type_code = models.CharField(max_length=50, primary_key=True)
    location_type_desc = models.CharField(max_length=255)
    status_flag = models.CharField(max_length=1)
    remark = models.CharField(max_length=2000)
    class Meta:
        db_table = u'rt_location_type'

class RtMethod(models.Model):
    method_code = models.CharField(max_length=50, primary_key=True)
    method_name = models.CharField(max_length=255)
    method_desc = models.CharField(max_length=500,null=True,blank=True)
    status_flag = models.CharField(max_length=1)
    remark = models.CharField(max_length=2000,null=True,blank=True)
    base_method = models.CharField(max_length=50,null=True,blank=True)
    userid = models.CharField(max_length=20)
    timestamp_created = models.DateTimeField(default= datetime.datetime.now())    
    def __unicode__(self):
        return u'%s %s' % (self.method_code, self.method_name)    
    class Meta:
        db_table = u'rt_method'

class RtMethodParameters(models.Model):
    method_code = models.ForeignKey(RtMethod, db_column='method_code')
    param_id = models.IntegerField()
    param_type = models.CharField(max_length=20)
    param_name = models.CharField(max_length=255)
    param_desc = models.CharField(max_length=500)
    param_value = models.CharField(max_length=255)
    method_id = models.AutoField(primary_key=True)
    userid = models.CharField(max_length=20)
    class Meta:
        db_table = u'rt_method_parameters'

class DtContributors(models.Model):
    commons = models.ForeignKey(DtDataCommons)
    people = models.ForeignKey(DtPeople)
    project_title = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    remark = models.CharField(max_length=2000)
    class Meta:
        db_table = u'dt_contributors'

class DtLocation(models.Model):
    loc_id = models.CharField(max_length=60,primary_key=True)
    commons_id = models.IntegerField()
    loc_name = models.CharField(max_length=255)
    data_provider = models.CharField(max_length=20,blank=True)
    loc_desc = models.CharField(max_length=1000,blank=True)
    loc_type = models.CharField(max_length=255,blank=True)#ForeignKey(RtLocationType, db_column='loc_type')
    loc_purpose = models.CharField(max_length=255,blank=True)
    loc_county = models.CharField(max_length=80,blank=True)
    loc_state = models.CharField(max_length=10,blank=True)
    lat = models.FloatField(blank=True)
    lon = models.FloatField(blank=True)
    northbounding = models.FloatField(blank=True)
    southbounding = models.FloatField(blank=True)
    eastbounding = models.FloatField(blank=True)
    westbounding = models.FloatField(blank=True)
    remark = models.CharField(max_length=2000,blank=True)
    start_date = models.DateTimeField(blank=True)
    end_date = models.DateTimeField(blank=True)
    coord_system = models.CharField(max_length=255,blank=True)
    projection = models.CharField(max_length=255,blank=True)
    loc_order = models.IntegerField(blank=True)
    base_loc_id = models.CharField(max_length=60,blank=True)
    #django_id = models.AutoField(primary_key=True)
    unique_together = ("commons_id", "loc_id")
    def __unicode__(self):
        return u'%s %s' % (self.loc_id, self.loc_name)
    class Meta:
        db_table = u'dt_location'

class DtLocationParameter(models.Model):
    commons = models.ForeignKey(DtLocation)
    loc_id = models.CharField(max_length=60)
    param_id = models.IntegerField()
    param_name = models.CharField(max_length=255)
    param_value = models.CharField(max_length=255)
    param_unit = models.CharField(max_length=15)
    remark = models.CharField(max_length=2000)
    class Meta:
        db_table = u'dt_location_parameter'
class DtCatalog(models.Model):
    Status_Data_Choices = (('Data','Data'),('Application','Application'),)
    commons_id = models.IntegerField()#ForeignKey(DtDataCommons)
    cat_id = models.AutoField(primary_key=True)
    cat_name = models.CharField(max_length=255)

wsgi_apps/datacatalog/templates/editCat/1result.html
            <div>Commons ID: {{commonid}} </div> 
            <script>onloadfunction();//$('#ftool').buttonset();
                    $('.tbar').hover(function(){$(this).addClass("ui-state-hover");},function(){$(this).removeClass("ui-state-hover");});
                    $('#btnAdd').click(function(){
                            $('#tabs-1' ).html( '&nbsp;' ).load(  '/getcommon/?common_id=addnew');
                    });
                    $('#btnDel').click(function(){
                            $('#output2' ).html( '&nbsp;' ).load(  '/delcommon/?common_id=' + {{ commonid }});
                    });
/*$('#test').submit(function(data) {
                            var test_form = $('#test');
                            test_form.ajaxForm({
                            url : this.action,
                            dataType : 'json',
                            success : function(json){
                                if (json.errors != undefined)
                                    alert('erros');
                                    process_form_errors(json, login_form);
                                else
                                    alert('Inside success');
                                    return false;//alert('success')//do something if there aren't errors
                                }   
                            });
                            });
                                    /*$.ajax({ type: 'POST',
                                             url: '{{action}}'
                                             data: data1
                                             success: alert('Success');
                                            });
                                    return false;
                                });
                                function hide_form_errors()
                                {                           
                                    $('.errorlist').remove();
                                }

                                function process_form_errors(json, form)
                                {           
                                    hide_form_errors();
                                    form.clearForm();
                                    errors = json.errors;
    
                                    if (errors.__all__ != undefined)
                                        form.append(errors.__all__);

                                        prefix = form.find(":hidden[name='prefix']").val();

                                        prefix == undefined ? prefix = '' : prefix = prefix + '-';
                                    for (field in errors)
                                        $('#id_' + prefix + field).after(errors[field]);
                                }*/
            </script>
            <form id="test" action="{{action}}" method="post" >{% csrf_token %}
                {% for field in form %}
                <div class="fieldWrapper" height="100%" width="100%">
                    <div class="left" style="float:left;text-align:right;width:20%"> {{ field.label_tag }}:</div>
                    <div class="right" style="float:left;margin-left:15px;width:75%"> {{ field }} </div>
                    <div class="top"> {{ field.errors }}</div>
                 </div>
                 {% endfor %}
                <li>{{ form.DELETE }}</li>
                <div class="left" style="float:left;text-align:right;"></div>
                <div class="right" style="float:left;margin-left:15px;text-align:right">
                 <p><input id="btnAdd" class="tbar ui-button ui-widget ui-state-default ui-button-text-only ui-corner-right" type="button" value="Add New Record" />
                    <input id="btnDel" class="tbar ui-button ui-widget ui-state-default ui-button-text-only ui-corner-right" type="button" value="Delete Record" />
                    <input id="formsub" class="tbar ui-button ui-widget ui-state-default ui-button-text-only ui-corner-right" type="submit" value="Save Record" /></p>
                </div>
            </form>
            <div id="output2"></div>

wsgi_apps/datacatalog/templates/editCat/cat_result.html
             <script type="text/javascript" src="http://static.cybercommons.org/js/catalog/catalog.js"></script>
            <script>onloadfunction();setLabels();//$('#ftool').buttonset();
                    $('.tbar').hover(function(){$(this).addClass("ui-state-hover");},function(){$(this).removeClass("ui-state-hover");});
                    $('#btnAdd').click(function(){
                            $('#tabs-1' ).html( '&nbsp;' ).load(  'getcatalog/?catid=addnew&commons_id='.concat(commons_id));
                    });
                    $('#id_status_data').change(function() {
                        setLabels();
/*
                        var ss = $("select#id_status_data").val();
                        if ( ss == "Data" ){
                        $(idl_cat_method).text('Metadata: ');
                        }
                        else{

                        $(idl_cat_method).text('Application Method');
                        }
*/
                    });
                    $('#btnDel').click(function(){
                            $('#output2' ).html( '&nbsp;' ).load(  'delcatalog/?cat_id={{catid}}&common_id='.concat(commons_id),function(){ 
                                var idx = $("select#Select").attr("selectedIndex");
                                var selectobject=document.getElementById("Select");
                                if (idx == 0){catid = selectobject.options[1].value;}
                                else{s = idx-1; catid = selectobject.options[s].value; } radio22();} );
                    });
/*
                    $( "#dialogdel" ).dialog({ autoOpen: false,title:'Delete' });
                    $('#btnDel').click(function(){$( "#dialogdel" ).dialog('open');});
                    $('#btnDelYes').click(function(){ $('#output2' ).html( '&nbsp;' ).load('delcatalog/?cat_id='concat(catid) + '&common_id='.concat(commons_id));
                                                        radio11();
                                                        $( "#dialogdel" ).dialog('close');});    
                    $('#btnDelNo').click(function() {$( "#dialogdel" ).dialog('close'); } );
*/
                    $('#btnAddLoc').click(function(){
                            var ss = $("select#id_loc_id").val();
                            if (ss == ""){
                            $('#dlog').html( '&nbsp;' ).load( 'getlocation/?loc_id=addnew&commons_id='.concat(commons_id),function(){
                                    $( '#dialog' ).dialog({width:'800px',modal: true,title:'Location Table'});});
                            }
                            else{
                            $('#dlog').html( '&nbsp;' ).load( 'getlocation/?loc_id=' + ss + '&commons_id='.concat(commons_id),function(){
                                    $( '#dialog' ).dialog({width:'800px',modal: true,title:'Location Table'});});
                            }
                    });
                    $('#btnAddtype').click(function(){
                            var ss = $("select#id_cat_type").val();
                            if (ss == ""){
                            $('#dlog').html( '&nbsp;' ).load( 'gettype/?type_id=addnew&commons_id='.concat(commons_id),function(){
                                    $( '#dialog' ).dialog({width:'800px',modal: true,title:'Type Table'});});
                            }
                            else{
                            $('#dlog').html( '&nbsp;' ).load( 'gettype/?type_id=' + ss + '&commons_id='.concat(commons_id),function(){
                                    $( '#dialog' ).dialog({width:'800px',modal: true,title:'Type Table'});});
                            }
                    });
                    $('#btnAddmeth').click(function(){
                            var ss = $("select#id_cat_method").val();
                            if (ss == ""){
                            $('#dlog').html( '&nbsp;' ).load( 'getmethod/?method_id=addnew&commons_id='.concat(commons_id),function(){
                                    $( '#dialog' ).dialog({width:'800px',modal: true,title:'Method Table'});});
                            }
                            else{
                            $('#dlog').html( '&nbsp;' ).load( 'getmethod/?method_id=' + ss + '&commons_id='.concat(commons_id),function(){
                                    $( '#dialog' ).dialog({width:'800px',modal: true,title:'Method Table'});});
                            }
                    });
            </script>
            <h2> Cybercommons Catalog </h2>
            <div class="left" style="padding:1px;float:left;text-align:right;width:20%"><strong>Catalog ID</strong>:</div>
            <div class="right" style="padding:1px;float:left;margin-left:15px;width:75%"> {{ catid }} </div>
            <form id="test" action="{{action}}" method="post">{% csrf_token %}
                {% for field in form.visible_fields %}
                    {% if forloop.first %}
                        {% for hidden in form.hidden_fields %}
                            {{ hidden }}
                        {% endfor %}
                    {% endif %}
                <div id="div_{{field.name}}" class="fieldWrapper">
                    {% if field.name == 'cat_name' or field.name == 'status_data' or field.name == 'loc_id' %}
                    <div class="left" style="padding:1px;float:left;text-align:right;width:20%"><strong><label id="idl_{{ field.name }}" for="id_{{ field.name }}">{{ field.label }}</label></strong>:</div>
                    {% else %}
                    <div class="left" style="padding:1px;float:left;text-align:right;width:20%"><label id="idl_{{ field.name }}" for="id_{{ field.name }}">{{ field.label }}</label>:</div>
                    {% endif %}
                    <div class="right" style="padding:1px;float:left;margin-left:15px;width:75%">{{ field }} 
                    {% if field.name == 'loc_id' %} 
                    <input id="btnAddLoc" class="tbar ui-button ui-widget ui-state-default ui-button-text-only ui-corner-right" type="button" value="Location Record" />
                    {% endif %}
                    {% if field.name == 'cat_type' %}
                    <input id="btnAddtype" class="tbar ui-button ui-widget ui-state-default ui-button-text-only ui-corner-right" type="button" value="Type     Record" />
                    {% endif %}
                    {% if field.name == 'cat_method' %}
                    <input id="btnAddmeth" class="tbar ui-button ui-widget ui-state-default ui-button-text-only ui-corner-right" type="button" value="Method  Record" />
                    {% endif %}
                    </div>
                    <div class="top"> {{ field.errors }}</div>
                </div>
                 {% endfor %}
                <div class="left" style="float:left;text-align:right;"></div>
                <div class="right" style="float:left;margin-left:15px;text-align:right">
                 <p><input id="btnAdd" class="tbar ui-button ui-widget ui-state-default ui-button-text-only ui-corner-right" type="button" value="Add New Record" />
                    <input id="btnDel" class="tbar ui-button ui-widget ui-state-default ui-button-text-only ui-corner-right" type="button" value="Delete Record" />
                    <input id="formsub" class="tbar ui-button ui-widget ui-state-default ui-button-text-only ui-corner-right" type="submit" value="Save Record" /></p>
                </div>
            </form>
            <div style="clear:both">
                <div id="output2"></div>
            </div>

wsgi_apps/datacatalog/templates/editCat/catalog.html
{% extends "base_edit.html" %}
{% block content %}
                    <div id="control">
                        <select id="Select"  style="width:100%;" size="57" >
                            {% for val in data %}
                                <option value={{val.cat_id}}>{{val.cat_id}} : {{val.cat_name}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div id="result">
                        <div id="tabs">
                            <ul>
                                <li><a href="#tabs-1">Edit Catalog Items</a></li>
                                <li><a href="#tabs-2">Webservice</a></li>
                            </ul>
                            <div id="tabs-1"></div>
                            <div id="tabs-2">Webservice template add .</div>    
                    </div>
{% endblock %}

wsgi_apps/datacatalog/templates/editCat/ws2_results.html
            <h2>JSON-RPC Web Service</h2>
            <h3> {{ header }}(row={})</h3>
            <h4> Method Help</h4>
            <textarea id="id_remark" rows="15" cols="80" name="remark">
Inserts record in dt_catalog table.
    
Parameters:
    row - python dictionary of record to insert

    row = { 'commons_id':<value>,'cat_name':<value>,'loc_id':<value>,'status_data':<'Data or Application'>,
            'cat_desc':<optional>,'cat_method':<optional>,'cat_type':<optional>,'observed_date':<optional>,
            'observed_year':<optional>,'remark':<optional>,'status_flag':'A'}

        Primary Key : cat_id autogenerated

    Returns

        {'cat_id':<value>,'commons_id':<value>}

    param - dictionary having the following attributes

        * commons_id - reference to dt_data_commons table commons_id,
        * cat_name - name of cataloged item,
        data_provider -  name of who is providing data,
        cat_type - type of cataloged item. reference to dt_type table ,
        * loc_id - reference to dt_location,
        source_id - integer datatype can be used for misc grouping of data,
        cat_desc - Description of cataloged data,
        cat_method - reference rt_method table. catalog method,
        observed_date - cataloged item data observation date(General)
        remark - General remarks 
        observed_year - cataloged item data observered year
        custom_field_1 - custom data for cataloged item
        custom_field_2 - custom data for cataloged item
        status_flag - A is default for Active, I Inactive
        status_data - 'Data' - metadata for data 'Application' - metadata for applications
        userid - user who cataloged data
        timestamp_created - default to Now() - When item cataloged
        
        * required fields
        returns dictionary of primary keys inserted</textarea>
            <h4>Python Code Sample</h4>
            <textarea id="id_remark" rows="17" cols="80" name="remark">
from xmlrpclib import ServerProxy # Standard Python Library
from rpc4django.utils import CookieTransport # pip install rpc4django
        
username = 'username'
password ='password'
            
URL = '{{ rpclink }}'
                    
s = ServerProxy(URL, transport=CookieTransport())

row = {'commons_id':<value>,'cat_name':<value>,'loc_id':<value>,'status_data':<'Data' or 'Application'>}

# Login Required Operation need! Insert operations
if s.system.login(username, password):
    catItems = s.{{ method }}(row)</textarea>
<h4> Cybercommons Web Services</h4>
<a href="RPC/">JSON-RPC Available Web Services</a>

wsgi_apps/datacatalog/templates/editCat/ws3_results.html
            <h2>JSON-RPC Web Service</h2>
            <h3> {{ header }}(row={},evtResult=[{},])</h3>
            <h4> Method Help</h4>
            <textarea id="id_remark" rows="15" cols="80" name="remark">
Inserts record in dt_event table and inserts list of dictionary records int dt_result table. 
    
Parameters:
    row - python dictionary of record to insert

    row = { 'commons_id':<value>,'cat_id':<value>,'event_name':<value>,'event_method':<value>,
         'event_desc':<optional>,'event_type':<optional>, 'event_date':<optional>,'remark':<optional>}

    Primary Key : event_id autogenerated

    evtResult = [{'commons_id':<value>, 'var_id':<value>, 'result_text'<value>,'result_order':<optional>,
                 'remark':<optional>}]

Returns
    {'Success':'Boolean','dt_event':{pkeys:<value>},'dt_result':[{pkeys}]}</textarea>
            <h4>Python Code Sample</h4>
            <textarea id="id_remark" rows="17" cols="80" name="remark">
from xmlrpclib import ServerProxy # Standard Python Library
from rpc4django.utils import CookieTransport # pip install rpc4django
        
username = 'username'
password ='password'
            
URL = '{{rpclink}}'
                    
s = ServerProxy(URL, transport=CookieTransport())

row = {'commons_id':<value>,'cat_id':<value>,'event_name':<value>,'event_method':<value>}
evtResult = [{'commons_id':<value>, 'var_id':<value>, 'result_text'<value>,]

# Login Required Operation need! Insert operations
if s.system.login(username, password):
    catItems = s.{{ method }}(row,evtResult)</textarea>
<h4> Cybercommons Web Services</h4>
<a href="RPC/">JSON-RPC Available Web Services</a>

wsgi_apps/datacatalog/templates/editCat/ws_results.html
            <h2>JSON-RPC Web Service</h2>
            <h3> {{ header }}(row={})</h3>
            <h4> Method Help</h4>
            <textarea id="id_remark" rows="15" cols="80" name="remark">
Inserts record in dt_data_commons table and assigns owner of commons to user.
    
    Parameters:
        row - python dictionary of record to insert

        row = { 'commons_name':<value>,'commons_code':<value>,'commons_desc':<optional>, 
                'commons_type':<optional>,'data_provider':<optional>, 'program_code':<optional>,'status_flag':'A'}

        Primary Key : commons_id autogenerated
    Returns
        {'Success':'Boolean','key':{commons_id:<value>}}</textarea>
            <h4>Python Code Sample</h4>
            <textarea id="id_remark" rows="17" cols="80" name="remark">
from xmlrpclib import ServerProxy # Standard Python Library
from rpc4django.utils import CookieTransport # pip install rpc4django
        
username = 'username'
password ='password'
            
URL = '{{ rpclink }}'
                    
s = ServerProxy(URL, transport=CookieTransport())

row = {'commons_name':<value>,'commons_code':<value>,'commons_desc':<optional>}

# Login Required Operation need! Insert operations
if s.system.login(username, password):
    catItems = s.{{ method }}(row)</textarea>
<h4> Cybercommons Web Services</h4>
<a href="RPC/">JSON-RPC Available Web Services</a>